name: Build and Push Docker Image

on:
  push:
    branches:
      - main # You can change this to your default branch
  pull_request:
    branches:
      - main # This triggers when a PR is created to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Runner to use for building the Docker image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # This checks out your repo code into the runner

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pythonapp:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pythonapp:latest
